### ISSUE TITLE
Inaccurate gerrit version parsing

### ISSUE THREAD

**Issue by dvsekhvalnov** [holmari/gerritstats#13]
Given gerrit version 2.12

Attempt to fetch json failing with:

```Java
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at com.holmsted.gerrit.GerritVersion.fromString(GerritVersion.java:25)
	at com.holmsted.gerrit.downloaders.ssh.GerritSsh.version(GerritSsh.java:27)
	at com.holmsted.gerrit.downloaders.Downloader.download(Downloader.java:45)
	at com.holmsted.gerrit.GerritStatsDownloaderMain.main(GerritStatsDownloaderMain.java:17)
```

**Comment by holmari** [comment]
I tested the version code with 3 different gerrit versions but did not run into this. @dvsekhvalnov, I'd really appreciate a PR to fix this, it's probably a pretty simple fix in that `fromString` method.

**Comment by dvsekhvalnov** [comment]
here you go.

**Comment by hawkeyej** [comment]
I think that there is still a problem with version parsing.

I have gerrit version 2.13.9 and the generated web page shows "Unknonw Gerrit Version Warning"
```
gerrit version 2.13.9
```
![image](https://user-images.githubusercontent.com/6677049/33342760-cd221a40-d448-11e7-861c-5166eda407b9.png)
