### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by Jossif** [holmari/gerritstats#41]
Hi, I tried to build the project on my mac running High Sierra, I'm getting this:

`In file included from ../../nan/nan.h:192:
../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../src/binding.cpp:1:
../../nan/nan.h:834:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/jossiftomash/.node-gyp/10.11.0/include/node/node.h:174:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/jossiftomash/.node-gyp/10.11.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/binding.cpp:1:
../../nan/nan.h:849:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/jossiftomash/.node-gyp/10.11.0/include/node/node.h:167:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/jossiftomash/.node-gyp/10.11.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/binding.cpp:1:
../../nan/nan.h:864:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/jossiftomash/.node-gyp/10.11.0/include/node/node.h:160:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/jossiftomash/.node-gyp/10.11.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/binding.cpp:1:
../../nan/nan.h:1473:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/jossiftomash/.node-gyp/10.11.0/include/node/node.h:174:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/jossiftomash/.node-gyp/10.11.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
4 warnings and 1 error generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/jossiftomash/source/gerritstats/GerritStats/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/Cellar/node/10.11.0/bin/node" "/Users/jossiftomash/source/gerritstats/GerritStats/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/jossiftomash/source/gerritstats/GerritStats/node_modules/node-sass
gyp ERR! node -v v10.11.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jossiftomash/.npm/_logs/2018-10-04T13_33_58_361Z-debug.log
:GerritStats:npmSetup FAILED`

**Comment by toniihsia** [comment]
Also having this issue

**Comment by Ziver** [comment]
I'm also having this issue.

**Comment by 0ren** [comment]
Running into the same issue on mojave (10.14.3). I see the following near the top of the output from ./gradelw assemble

```
> node-sass@3.13.1 install /Users/olevin/workspace/gerritstats/GerritStats/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/darwin-x64-67_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/darwin-x64-67_binding.node": 

HTTP error 404 Not Found
```

**Comment by biaji** [comment]
Just downgrade node to 8. Then it go smooth.

**Comment by atinmu** [comment]
Having the same issue. 

@biaji What do you mean by 'downgrade node to 8?' Do you mean nodejs version to 8?

**Comment by biaji** [comment]
yes ，exactly

Atin Mukherjee <notifications@github.com> 于 2019年5月1日周三 下午3:48写道：

**Comment by henriquemattos** [comment]
I'm running on macOS Catalina with Node v13 and could have a successful build after the following:

In my case it was missing the path to XCode used by node-gyp, a node module that node-sass depends on. But even though I installed XCode `xcode-select --install` and set it to use not the command-line but the app with `sudo xcode-select -s /Applications/Xcode-beta.app/Contents/Developer`, still I had to manually enter the folder GerritStats and upgrade node-sass to latest to have the latest node-gyp: `npm install -y node-sass@latest`.

After that I could run ./gradlew assemble successfully. 🍀

ps.: I'm running on macOS Catalina (10.15.3 (19D76))

**Comment by chrisinmtown** [comment]
Please test again, I cannot change the status of this issue but @holmari recently merged #48 which fixed the build in my local environment, which is Mac OSX and this JDK

java 11.0.4 2019-07-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.4+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.4+10-LTS, mixed mode)

**Comment by Ziver** [comment]
@henriquemattos Thanks! running that command under the GerritStats folder solved my build issue.
